export const USUARIO_AUTENTICADO = "USUARIO_AUTENTICADO";
export const USUARIO_REGISTRO_EXITO = "USUARIO_REGISTRO_EXITO";
export const USUARIO_REGISTRO_ERROR = "USUARIO_REGISTRO_ERROR";
export const INICIAR_SESION = "INICIAR_SESION";
export const LOGIN_EXITO = "LOGIN_EXITO";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const CERRAR_SESION = "CERRAR_SESION";

export const MOSTRAR_ALETAS = "MOSTRAR_ALETAS";
export const LIMPIAR_ALERTAS = "LIMPIAR_ALERTAS";

export const SUBIENDO_ARCHIVO = "SUBIENDO_ARCHIVO";
export const SUBIR_ARCHIVO_EXITO = "SUBIR_ARCHIVO_EXITO";
export const SUBIR_ARCHIVO_ERROR = "SUBIR_ARCHIVO_ERROR";
export const CREAR_ENLACE_EXITO = "CREAR_ENLACE_EXITO";
export const CREAR_ENLACE_ERROR = "CREAR_ENLACE_ERROR";

export const LIMPIAR_STATE = "LIMPIAR_STATE";

export const AGREGAR_PASSWORD = "AGREGAR_PASSWORD";
export const AGREGAR_DESCARGAS = "AGREGAR_DESCARGAS";

export const LISTA_ENLACES = "LISTA_ENLACES";
export const LISTA_ENLACES_ELIMINAR_EXITO = "LISTA_ENLACES_ELIMINAR_EXITO";

