export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO'
export const USUARIO_REGISTRO_EXITO = 'USUARIO_REGISTRO_EXITO'
export const USUARIO_REGISTRO_ERROR = 'USUARIO_REGISTRO_ERROR'
export const LIMPIAR_ALERTAS = 'LIMPIAR_ALERTAS'